// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfsujgybrrfufglqdhoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmc3VqZ3licnJmdWZnbHFkaG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODk5ODYsImV4cCI6MjA2MTk2NTk4Nn0.3Cb6RdVu1_roFh6G9h7ScEk5jPOnHTGG6j90bHwwU0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);